### ISSUE TITLE
Reference to archived depedency

### ISSUE THREAD

**Issue by phaumer** [IBM/ibm-cloud-sdk-common#55]
The documentation explaining how to use the node SDK behind a proxy here: <https://github.com/IBM/ibm-cloud-sdk-common?tab=readme-ov-file#configuring-the-http-client> recommends creating a dependency using this project <https://github.com/koichik/node-tunnel/>. However, the project is archived and not updated for 6 years. Requiring such as project is against IBM policy as it could introduce security risks. Please, provide a recommendation that we can use for IBM approved projects.

**Comment by dpopp07** [comment]
Good catch. That is definitely outdated and should be removed.

It was originally added as a workaround because `axios`, the underlying HTTP library we use, had a bug that prevented usage in this scenario. That package has been updated a lot since then.

Have you tried to use the SDK behind a proxy lately? I'd be curious to see if a workaround is even still necessary.

**Comment by phaumer** [comment]
A customer we are working with suggested this library: <https://github.com/TooTallNate/proxy-agents/tree/main/packages/https-proxy-agent> 

Does this fulfill all the requirements needed to replace the node-tunnel library and could be officially endorsed by IBM? Any other alternatives available?

**Comment by dpopp07** [comment]
@phaumer as discussed internally, yes - that package looks like an ideal alternative. I will open a PR to address this shortly.
